server:
  port: 9090
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/service-product/** # Redirige les requêtes commençant par /product-service/
          filters:
            - RewritePath=/service-product(?<segment>/?.*), $\{segment}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}