version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ecommerce_postgres
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - /Users/ouisoft/WorkSpace/Docker/volumes/postgres/data:/data/postgres
      - /Users/ouisoft/WorkSpace/Docker/volumes/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - ecommerce_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ecommerce"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: ecommerce_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - /Users/ouisoft/WorkSpace/Docker/volumes/postgres/pgadmin:/var/lib/pgadmin
    networks:
      - ecommerce_network
    depends_on:
      postgres:
        condition: service_healthy
networks:
  ecommerce_network:
    name: ecommerce_network
    driver: bridge