server:
  port: '0'
spring:
  application:
    name: service-product
  #configuration database
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    url: jdbc:postgresql://localhost:5432/ecommerce
    user: user
    password: password
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: false
  instance:
    instance-id: ${spring.application.name}:${random.value}